### ISSUE TITLE
https的目标无法检测

### ISSUE THREAD

**Issue by k3mlol** [Veraxy00/Jumpserver-EXP#1]
如果走wss的话，貌似会存在bug，可以读取到日志，但是无法获取到shell

**Comment by Veraxy00** [comment]
考虑更新代码，方便提供https目标测试环境吗

**Comment by Veraxy00** [comment]
@k3mlol 考虑更新代码，方便提供https目标测试环境吗

**Comment by k3mlol** [comment]
> 考虑更新代码，方便提供https目标测试环境吗

我也没搭建环境，直接测试生产的，我是直接改代码
https://github.com/Veraxy00/Jumpserver-EXP/blob/main/jumpserver-exp.py#L123
为wss还是不行。

**Comment by Veraxy00** [comment]
> > 考虑更新代码，方便提供https目标测试环境吗
> 
> 我也没搭建环境，直接测试生产的，我是直接改代码
> https://github.com/Veraxy00/Jumpserver-EXP/blob/main/jumpserver-exp.py#L123
> 为wss还是不行。

好滴吧，应该是需要本地创建证书，类似于：

`ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)`
`localhost_pem = pathlib.Path(__file__).with_name("cert.pem") `
`ssl_context.load_verify_locations(localhost_pem)`

创建websocket连接的代码改成ssl安全连接：

比如：https://github.com/Veraxy00/Jumpserver-EXP/blob/main/jumpserver-exp.py#L16
改成 `async with websockets.connect(tar, ssl=ssl_context) as client:`

**Comment by k3mlol** [comment]
👌，我测试通过的话，和您说

**Comment by Veraxy00** [comment]
> 👌，我测试通过的话，和您说

嗯呢

**Comment by k3mlol** [comment]
不行了。。。有好用的websocket的客户端吗？报错：
server rejected WebSocket connection: HTTP 404

直接用客户端连上去算了。脚本太复杂了。
我加了

``` python
    ssl_context = ssl.SSLContext()
    ssl_context.check_hostname = False
    ssl_context.verify_mode = ssl.CERT_NONE
    async with websockets.connect(target, ssl=ssl_context) as websocket:
```
